import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@/components/context/user';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang='en'>
        <body
          style={{ maxHeight: '100vh', overflow: 'hidden' }}
          className={inter.className}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </UserProvider>
  );
}
